interface FlagIconProps {
  country: string
  className?: string
}

export function FlagIcon({ country, className = "w-5 h-5" }: FlagIconProps) {
  const flagMap: Record<string, string> = {
    'BD': '🇧🇩',
    'IN': '🇮🇳', 
    'PK': '🇵🇰',
    'US': '🇺🇸',
    'GB': '🇬🇧',
    'CA': '🇨🇦',
    'AU': '🇦🇺',
    'AE': '🇦🇪',
    'SA': '🇸🇦',
    'MY': '🇲🇾',
    'SG': '🇸🇬',
    'TH': '🇹🇭',
    'JP': '🇯🇵',
    'KR': '🇰🇷',
    'CN': '🇨🇳',
    'HK': '🇭🇰',
    'ID': '🇮🇩',
    'PH': '🇵🇭',
    'VN': '🇻🇳',
    'LK': '🇱🇰',
    'NP': '🇳🇵',
    'BT': '🇧🇹',
    'MM': '🇲🇲',
    'MV': '🇲🇻',
    'OM': '🇴🇲',
    'QA': '🇶🇦',
    'KW': '🇰🇼',
    'BH': '🇧🇭',
    'TR': '🇹🇷',
    'IR': '🇮🇷',
    'AF': '🇦🇫',
    'DE': '🇩🇪',
    'FR': '🇫🇷',
    'IT': '🇮🇹',
    'ES': '🇪🇸',
    'NL': '🇳🇱',
    'BE': '🇧🇪',
    'CH': '🇨🇭',
    'AT': '🇦🇹',
    'SE': '🇸🇪',
    'NO': '🇳🇴',
    'DK': '🇩🇰',
    'FI': '🇫🇮',
    'RU': '🇷🇺',
    'BR': '🇧🇷',
    'AR': '🇦🇷',
    'MX': '🇲🇽',
    'ZA': '🇿🇦',
    'EG': '🇪🇬',
    'NG': '🇳🇬',
    'KE': '🇰🇪',
    'TZ': '🇹🇿',
    'UG': '🇺🇬',
    'GH': '🇬🇭',
    'IL': '🇮🇱',
    'JO': '🇯🇴',
    'LB': '🇱🇧',
    'IQ': '🇮🇶',
    'SY': '🇸🇾',
    'CY': '🇨🇾',
    'GR': '🇬🇷',
    'PT': '🇵🇹',
    'IE': '🇮🇪',
    'IS': '🇮🇸',
    'LU': '🇱🇺',
    'MT': '🇲🇹',
    'CZ': '🇨🇿',
    'SK': '🇸🇰',
    'HU': '🇭🇺',
    'PL': '🇵🇱',
    'RO': '🇷🇴',
    'BG': '🇧🇬',
    'HR': '🇭🇷',
    'SI': '🇸🇮',
    'EE': '🇪🇪',
    'LV': '🇱🇻',
    'LT': '🇱🇹',
    'UA': '🇺🇦',
    'BY': '🇧🇾',
    'MD': '🇲🇩',
    'AL': '🇦🇱',
    'MK': '🇲🇰',
    'RS': '🇷🇸',
    'ME': '🇲🇪',
    'BA': '🇧🇦',
    'AD': '🇦🇩',
    'MC': '🇲🇨',
    'SM': '🇸🇲',
    'VA': '🇻🇦',
    'LI': '🇱🇮',
    'NZ': '🇳🇿',
    'FJ': '🇫🇯',
    'PG': '🇵🇬',
    'SB': '🇸🇧',
    'VU': '🇻🇺',
    'NC': '🇳🇨',
    'PF': '🇵🇫',
    'CK': '🇨🇰',
    'TO': '🇹🇴',
    'WS': '🇼🇸',
    'KI': '🇰🇮',
    'TV': '🇹🇻',
    'NU': '🇳🇺',
    'NR': '🇳🇷',
    'PW': '🇵🇼',
    'FM': '🇫🇲',
    'MH': '🇲🇭',
    'GU': '🇬🇺',
    'MP': '🇲🇵',
    'AS': '🇦🇸',
    'VI': '🇻🇮',
    'PR': '🇵🇷',
    'BM': '🇧🇲',
    'KY': '🇰🇾',
    'TC': '🇹🇨',
    'VG': '🇻🇬',
    'AI': '🇦🇮',
    'MS': '🇲🇸',
    'GD': '🇬🇩',
    'BB': '🇧🇧',
    'TT': '🇹🇹',
    'JM': '🇯🇲',
    'BS': '🇧🇸',
    'DO': '🇩🇴',
    'HT': '🇭🇹',
    'PA': '🇵🇦',
    'CR': '🇨🇷',
    'GT': '🇬🇹',
    'SV': '🇸🇻',
    'HN': '🇭🇳',
    'NI': '🇳🇮',
    'CO': '🇨🇴',
    'VE': '🇻🇪',
    'EC': '🇪🇨',
    'PE': '🇵🇪',
    'BO': '🇧🇴',
    'PY': '🇵🇾',
    'UY': '🇺🇾',
    'GY': '🇬🇾',
    'SR': '🇸🇷',
    'GF': '🇬🇫',
    'CL': '🇨🇱'
  }

  const flag = flagMap[country] || '🏳️'

  return (
    <span 
      className={className}
      style={{ 
        fontFamily: 'Apple Color Emoji, Segoe UI Emoji, Noto Color Emoji, Emoji, sans-serif',
        fontSize: '1.25rem',
        lineHeight: 1
      }}
    >
      {flag}
    </span>
  )
}
